server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql:///student?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
mybatis-plus:
  mapper-locations: classpath:com/qf/dao/*.xml
  type-aliases-package: com.qf.entity
